# Site settings
title: You Are Here
email: logan.williams@alum.mit.edu
description: > # this means to ignore newlines until "baseurl:"
  Photoblog of Logan Williams.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://enclav.es" # the base hostname & protocol for your site
twitter_username: obtusatum
github_username:  loganwilliams

# Build settings
markdown: kramdown
